#!/usr/bin/bash

build() {
  add_binary /usr/bin/blkid
  add_binary /usr/bin/mount
  add_binary /usr/bin/umount
  add_binary /usr/bin/readlink
  add_runscript
}

help() {
  cat <<'EOF'
Marker-first persistence autodetect for archiso cow_label.
EOF
}
