[options]
CacheDir = /var/cache/pacman/pkg/ 
HookDir = /home/kitten/Documents/choutoulu-profile/.tmp/kitest-work/x86_64/airootfs/etc/pacman.d/hooks/
GPGDir = /etc/pacman.d/gnupg/
HoldPkg = pacman
HoldPkg = glibc
Architecture = x86_64
ParallelDownloads = 3
CleanMethod = KeepInstalled
SigLevel = PackageRequired
SigLevel = PackageTrustedOnly
SigLevel = DatabaseOptional
SigLevel = DatabaseTrustedOnly
LocalFileSigLevel = PackageOptional
LocalFileSigLevel = PackageTrustedOnly
[kitten-local]
Usage = All
SigLevel = PackageOptional
SigLevel = PackageTrustAll
SigLevel = DatabaseOptional
SigLevel = DatabaseTrustAll
Server = file:///var/tmp/kitest-localrepo
[core]
Usage = All
Server = https://mirror.rackspace.com/archlinux/core/os/x86_64
Server = https://mirror.leaseweb.com/archlinux/core/os/x86_64
Server = https://geo.mirror.pkgbuild.com/core/os/x86_64
[extra]
Usage = All
Server = https://mirror.rackspace.com/archlinux/extra/os/x86_64
Server = https://mirror.leaseweb.com/archlinux/extra/os/x86_64
Server = https://geo.mirror.pkgbuild.com/extra/os/x86_64
