# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# Pacman backend — netinstall populates install lists via Global Storage.
---
backend: pacman

skip_if_no_internet: false
update_db: true
update_system: false

pacman:
  num_retries: 2
  disable_download_timeout: false
  needed_only: true

operations: []
