# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# Regenerate initramfs after optional packages (e.g. NVIDIA modules).
---
dontChroot: false
timeout: 900
verbose: true

i18n:
  name: "Regenerate initramfs"

script:
  - command: "/bin/sh -c '/usr/bin/mkinitcpio -P'"
    timeout: 900
