# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
dontChroot: false
timeout: 3600
verbose: true

script:
  - command: "/bin/sh -c 'export KITEST_PC=\"${gs[packagechooser_flatpak]}\"; exec /usr/local/bin/kitest-calamares-flatpak.sh'"
    timeout: 3600
