# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
dontChroot: false
timeout: 120
verbose: false

i18n:
  name: "Remove live installer"

script:
  - command: "/usr/local/bin/kitest-calamares-cleanup.sh"
    timeout: 120
