# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# Archiso layout: ${install_dir}/${arch}/airootfs.sfs on the ISO (see profiledef install_dir).
---
unpack:
  - source: "/run/archiso/bootmnt/arch/x86_64/airootfs.sfs"
    sourcefs: "squashfs"
    destination: ""
