# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false
showDonateUrl: false

requirements:
  requiredStorage: 4.0
  requiredRam: 1.0
  internetCheckUrl: ""
  check:
    - storage
    - ram
    - power
    - screen
  required:
    - ram

geoip:
  style: "json"
  url: "https://geoip.kde.org/v1/calamares"
  selector: ""
