# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
modules-search: [ local ]

instances:
  - id: bundles
    module: netinstall
    config: netinstall-bundles.conf
  - id: flatpak
    module: packagechooser
    config: packagechooser-flatpak.conf
  - id: flatpak-install
    module: shellprocess
    config: shellprocess-flatpak.conf
  - id: mkinitcpio-after-pkgs
    module: shellprocess
    config: shellprocess-mkinitcpio.conf
  - id: cleanup-installer
    module: shellprocess
    config: shellprocess-cleanup.conf

sequence:
  - show:
      - welcome
      - netinstall@bundles
      - packagechooser@flatpak
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - locale
      - keyboard
      - localecfg
      - fstab
      - initcpiocfg
      - initcpio
      - removeuser
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - services-systemd
      - packages
      - shellprocess@mkinitcpio-after-pkgs
      - bootloader
      - shellprocess@flatpak-install
      - shellprocess@cleanup-installer
      - umount
  - show:
      - finished

branding: kitten

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false
